# Generated by Django 4.1.7 on 2023-10-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="course",
            field=models.IntegerField(
                choices=[(492, "Section 492"), (493, "Section 493")], default=492
            ),
            preserve_default=False,
        ),
    ]
