# Generated by Django 4.1.7 on 2023-10-21 20:18

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=30, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="student_id",
            field=models.CharField(
                blank=True,
                max_length=9,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(9),
                    django.core.validators.MaxLengthValidator(9),
                    accounts.models.validate_integer,
                ],
                verbose_name="Student ID",
            ),
        ),
    ]
