# Generated by Django 4.1.7 on 2023-10-23 03:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_studentprofile_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentprofile",
            old_name="course",
            new_name="section",
        ),
    ]
