# Generated by Django 4.1.7 on 2023-04-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_options_customuser_date_joined_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_volunteer",
            field=models.BooleanField(default=False),
        ),
    ]
