# Generated by Django 4.1.7 on 2023-10-23 03:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_course_studentprofile_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="section",
        ),
    ]
