# Generated by Django 4.1.7 on 2023-04-13 06:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_email_confirmed_alter_userprofile_user"),
        ("accounts", "0003_userprofile_is_volunteer"),
    ]

    operations = []
