# Generated by Django 4.1.7 on 2023-04-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_userprofile_student_id_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_team_lead",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="student_id",
            field=models.CharField(blank=True, default="", max_length=10, unique=True),
        ),
    ]
