# Generated by Django 4.1.7 on 2023-10-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_professorprofile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professorprofile",
            name="csun_faculty_page_link",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="professorprofile",
            name="rate_my_professor_link",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
