# Generated by Django 4.1.7 on 2023-04-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_customuser_is_team_lead_alter_userprofile_student_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="student_id",
        ),
        migrations.AddField(
            model_name="customuser",
            name="student_id",
            field=models.CharField(blank=True, default="", max_length=9, unique=True),
        ),
    ]
