# Generated by Django 4.1.7 on 2023-04-21 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_remove_userprofile_student_id_customuser_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="student_id",
            field=models.CharField(
                default="",
                max_length=9,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(9),
                    django.core.validators.MaxLengthValidator(9),
                ],
            ),
        ),
    ]
