# Generated by Django 4.1.7 on 2023-10-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_remove_professorprofile_rate_my_professor_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professorprofile",
            name="csun_faculty_page_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="professorprofile",
            name="rate_my_professor_difficulty",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="professorprofile",
            name="rate_my_professor_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="professorprofile",
            name="rate_my_professor_would_take_again",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
