# Generated by Django 4.1.7 on 2023-04-21 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email_confirmed",
            field=models.BooleanField(default=False, verbose_name="email confirmed"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=30, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_professor",
            field=models.BooleanField(default=False, verbose_name="professor"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="staff"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_student",
            field=models.BooleanField(default=False, verbose_name="student"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_team_lead",
            field=models.BooleanField(default=False, verbose_name="team lead"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=30, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="student_id",
            field=models.CharField(
                max_length=9,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(9),
                    django.core.validators.MaxLengthValidator(9),
                ],
                verbose_name="Student ID",
            ),
        ),
    ]
