# Generated by Django 4.1.7 on 2023-10-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_professorprofile_csun_faculty_page_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professorprofile",
            name="rate_my_professor_difficulty",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="professorprofile",
            name="rate_my_professor_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="professorprofile",
            name="rate_my_professor_would_take_again",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
