# Generated by Django 4.1.7 on 2023-10-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0009_alter_professorprofile_rate_my_professor_difficulty_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="professorprofile",
            name="csun_faculty_page_link",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
