# Generated by Django 4.1.7 on 2023-10-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_professorprofile_csun_faculty_page_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professorprofile",
            name="csun_faculty_page_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
