# Generated by Django 4.1.7 on 2023-05-29 06:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_customuser_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_confirmed",
            field=models.BooleanField(default=False, verbose_name="email confirmed"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_professor",
            field=models.BooleanField(default=False, verbose_name="professor"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_student",
            field=models.BooleanField(default=False, verbose_name="student"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_team_lead",
            field=models.BooleanField(default=False, verbose_name="team lead"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(default="", max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=30, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="staff"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=30, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="student_id",
            field=models.CharField(
                max_length=9,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(9),
                    django.core.validators.MaxLengthValidator(9),
                ],
                verbose_name="Student ID",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_volunteer",
                    models.BooleanField(default=False, verbose_name="volunteer"),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resumes/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
