# Generated by Django 4.1.7 on 2023-10-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_professorprofile_csun_faculty_page_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professorprofile",
            name="rate_my_professor_difficulty",
        ),
        migrations.RemoveField(
            model_name="professorprofile",
            name="rate_my_professor_rating",
        ),
        migrations.RemoveField(
            model_name="professorprofile",
            name="rate_my_professor_would_take_again",
        ),
        migrations.AddField(
            model_name="professorprofile",
            name="rate_my_professor_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
