# Generated by Django 4.1.7 on 2023-12-30 04:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0012_remove_professorprofile_rate_my_professor_difficulty_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professorprofile",
            name="rate_my_professor_link",
        ),
    ]
