# Generated by Django 4.1.7 on 2023-05-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="team_lead",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
