# Generated by Django 4.1.7 on 2023-05-30 05:09

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_project_meeting_schedule"),
        ("accounts", "0016_alter_studentprofile_team_lead"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="student_id",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="student_id",
            field=models.CharField(
                default=123456789,
                max_length=9,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(9),
                    django.core.validators.MaxLengthValidator(9),
                    accounts.models.validate_integer,
                ],
                verbose_name="Student ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="professorprofile",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="professors", to="projects.project"
            ),
        ),
    ]
