# Generated by Django 4.1.7 on 2023-06-08 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_remove_customuser_student_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamLeadProfile",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.studentprofile",),
        ),
    ]
