# Generated by Django 4.1.7 on 2023-05-30 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeetingTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("MON", "M"),
                            ("TUE", "T"),
                            ("WED", "W"),
                            ("THU", "Th"),
                            ("FRI", "F"),
                            ("SAT", "S"),
                            ("SUN", "Su"),
                        ],
                        max_length=3,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100, unique=True)),
                (
                    "open_slots",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(2)],
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(2)],
                    ),
                ),
                (
                    "relevant_skills",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "meeting_schedule",
                    models.ManyToManyField(
                        blank=True, null=True, to="projects.meetingtime"
                    ),
                ),
            ],
        ),
    ]
