# Generated by Django 4.1.7 on 2023-10-23 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100, unique=True)),
                (
                    "project_description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "open_slots",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(99)]
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(99)]
                    ),
                ),
                (
                    "relevant_skills",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("meeting_schedule", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
