# Generated by Django 4.1.7 on 2023-04-12 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100)),
                ("professor_name", models.CharField(max_length=100)),
                ("open_spots", models.PositiveIntegerField(max_length=20)),
                ("total_spots", models.PositiveIntegerField(max_length=100)),
                ("project_description", models.TextField()),
                ("neccesary_skills", models.TextField()),
                ("meeting_times", models.TextField()),
                (
                    "student_list",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="SeniorProject",
        ),
    ]
