# Generated by Django 4.1.7 on 2023-05-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="meeting_schedule",
            field=models.ManyToManyField(to="projects.meetingtime"),
        ),
    ]
