# Generated by Django 4.1.7 on 2023-05-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_project_meeting_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_description",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
