# Generated by Django 4.1.7 on 2023-04-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_projectprofile_delete_seniorproject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectprofile",
            name="open_spots",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="projectprofile",
            name="total_spots",
            field=models.PositiveIntegerField(),
        ),
    ]
