# Generated by Django 4.1.7 on 2023-05-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_project_project_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
