# Generated by Django 4.1.7 on 2023-06-08 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_project_project_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="capacity",
            field=models.IntegerField(
                default=99, validators=[django.core.validators.MaxValueValidator(2)]
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="open_slots",
            field=models.IntegerField(
                default=99, validators=[django.core.validators.MaxValueValidator(2)]
            ),
            preserve_default=False,
        ),
    ]
