# Generated by Django 4.1.7 on 2023-04-13 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0004_dayofweek_meetingtime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectprofile",
            name="student_list",
        ),
        migrations.AddField(
            model_name="projectprofile",
            name="student_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
