# Generated by Django 4.1.7 on 2023-06-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_project_capacity_alter_project_open_slots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingtime",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("MON", "Monday"),
                    ("TUE", "Tuesday"),
                    ("WED", "Wednesday"),
                    ("THU", "Thursday"),
                    ("FRI", "Friday"),
                    ("SAT", "Saturday"),
                    ("SUN", "Sunday"),
                ],
                max_length=3,
            ),
        ),
    ]
