# Generated by Django 4.1.7 on 2023-06-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_meetingtime_day_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingtime",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("MON", "M"),
                    ("TUE", "T"),
                    ("WED", "W"),
                    ("THU", "Th"),
                    ("FRI", "F"),
                    ("SAT", "S"),
                    ("SUN", "Su"),
                ],
                max_length=3,
            ),
        ),
    ]
