# Generated by Django 4.1.7 on 2023-06-09 23:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_project_meeting_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="meeting_schedule",
        ),
    ]
