# Generated by Django 4.1.7 on 2023-08-06 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_project_meeting_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="capacity",
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(99)]
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="open_slots",
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(99)]
            ),
        ),
    ]
