# Generated by Django 4.1.7 on 2023-10-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0013_alter_project_capacity_alter_project_open_slots"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="meeting_schedule",
        ),
        migrations.DeleteModel(
            name="MeetingTime",
        ),
        migrations.AddField(
            model_name="project",
            name="meeting_schedule",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
